### ISSUE TITLE
Delete Object

### ISSUE THREAD

**Issue by wwwroot** [poofik/WebGL-HousePlanner#2]
Hi, poofik

I see that object just remove selected object. But can I remove object?

**Comment by poofik** [comment]
It used to work, something changed within three.js

Within main.js we are calling "scene3DObjectSelectRemove()" function and removing from a group Object3D called "scene3DHouseContainer"

**Comment by poofik** [comment]
c143be3be9f6bbc13b771a726e8c4bb90359b6da
