### ISSUE TITLE
[HELP] Compressing js into jsz

### ISSUE THREAD

**Issue by wwwroot** [poofik/WebGL-HousePlanner#3]
Hi poofik,

I use windows 8, can you help me for step

Compressing js into jsz
Run Encode and Zip script

Cheers

**Comment by poofik** [comment]
.jsz is simply a .zip file of .js renamed to .jsz
https://github.com/Stuk/jszip is the library that reads the zip files.

**Comment by wwwroot** [comment]
Hi Poofik,

thanks for reply, but I try and I test, it's not work.
can I put obj file or just .js? in here

{
    "menu": [{
        "name": "Small Bush",
        "image": "./objects/Exterior/Trees/palm.jpg",
        "file": "./objects/Exterior/Trees/palm.js", <<< here
        "manufacturer": null,
        "model": null,
        "store": null,
        "price": null,
        "update": null
    },{
        "name": "untitled",
        "image": "./objects/Exterior/Trees/untitled.jpg",
        "file": "./objects/Exterior/Trees/untitled.obj", <<< and here
        "manufacturer": null,
        "model": null,
        "store": null,
        "price": null,
        "update": null
    }]
}

cheers

**Comment by wwwroot** [comment]
It's work bro, I just rename file js to json. Thanks

Cheers

**Comment by poofik** [comment]
3D models are exported from Blender using the old "io_mesh_threejs" exporter.
